# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# General setup
site_name: Composables
site_url: https://tunjid.github.io/Composable/
site_author: Adetunji Dahunsi
site_description: A collection of utility composable functions

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/tunjid/Composables
nav:
  - Home: index.md
  - Sticky Headers: implementation/sticky_headers.md
  - Collapsing Headers: implementation/collapsing_headers.md
  - Pointer Offset Scroll: implementation/pointer_offset.md
  - Scrollbars: implementation/scrollbars.md
  - Drag To Dismiss: implementation/drag_to_dismiss.md
  - Alignment / Content Scale Interpolation: implementation/interpolation.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences