# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# General setup
site_name: Tiler
site_url: https://tunjid.github.io/Tiler/
site_author: Adetunji Dahunsi
site_description: A reactive state based pagination library

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/tunjid/Tiler
nav:
  - Home: index.md
  - Tiled lists: implementation/tiledlist.md
  - Tiling use cases and examples:
      - Overview: usecases/overview.md
      - Basic Example: usecases/basic-example.md
      - Placeholders: usecases/placeholders.md
      - Search: usecases/search.md
      - Adaptive Paging: usecases/adaptive-paging.md
      - Adaptive Paged Search with Placeholders: usecases/complex-tiling.md
      - Transformations: usecases/transformations.md
      - Jetpack Compose: usecases/compose.md
  - How tiling works:
      - Primitives: implementation/primitives.md
      - Pivoting: implementation/pivoted-tiling.md
      - Pagination types and Tiling: implementation/pagination-types.md
      - Performance: implementation/performance.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences